version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ecommerce -d ecommerce_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://ecommerce:password123@db:5432/ecommerce_db}
      - PAYMENT_SERVICE_URL=http://pagos:8002
      - NOTIFICACIONES_URL=http://notificaciones:8003
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AUDITORIA_URL=http://auditoria:8004
    depends_on:
      db:
        condition: service_healthy
      pagos:
        condition: service_started

  pagos:
    build:
      context: ./pagos
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://ecommerce:password123@db:5432/ecommerce_db}
      - MP_ACCESS_TOKEN=APP_USR-4795680976904507-050513-d428dd1b2f4fd762db76d5b2e9a55735-3379497295
      - NOTIFICACIONES_URL=http://notificaciones:8003
      - MP_SUCCESS_URL=${MP_SUCCESS_URL}
      - MP_FAILURE_URL=${MP_FAILURE_URL}
      - MP_PENDING_URL=${MP_PENDING_URL}
      - MP_WEBHOOK_URL=${MP_WEBHOOK_URL}
      - AUDITORIA_URL=http://auditoria:8004
    depends_on:
      db:
        condition: service_healthy

  notificaciones:
    build:
      context: ./notificaciones
    ports:
      - "8003:8003"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - SES_SENDER_EMAIL=${SES_SENDER_EMAIL}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80"

  auditoria:
    build:
      context: ./auditoria
    ports:
      - "8004:8004"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://ecommerce:password123@db:5432/ecommerce_db}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:

    #holaaa
