name: CI/CD Pipeline to AWS ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY_FRONTEND: frontend-repo           # set this to your Amazon ECR repository name
  ECR_REPOSITORY_BACKEND: backend-repo           
  ECR_REPOSITORY_PAGOS: pagos-repo           
  ECS_CLUSTER: ecommerce-cluster                 # set this to your Amazon ECS cluster name
  ECS_SERVICE_FRONTEND: frontend-service                 # set this to your Amazon ECS service name
  ECS_SERVICE_BACKEND: backend-service                 
  ECS_SERVICE_PAGOS: pagos-service                 
  ECS_TASK_DEFINITION_FRONTEND: .aws/frontend-task-def.json # set this to the path to your Amazon ECS task definition
  ECS_TASK_DEFINITION_BACKEND: .aws/backend-task-def.json
  ECS_TASK_DEFINITION_PAGOS: .aws/pagos-task-def.json
  CONTAINER_NAME_FRONTEND: frontend-container
  CONTAINER_NAME_BACKEND: backend-container
  CONTAINER_NAME_PAGOS: pagos-container

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR (Frontend)
      id: build-image-frontend
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$IMAGE_TAG ./frontend
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Build, tag, and push image to Amazon ECR (Backend)
      id: build-image-backend
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG ./backend
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Build, tag, and push image to Amazon ECR (Pagos)
      id: build-image-pagos
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_PAGOS:$IMAGE_TAG ./pagos
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_PAGOS:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY_PAGOS:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Fill in the new image ID in the Amazon ECS task definition (Frontend)
      id: task-def-frontend
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.ECS_TASK_DEFINITION_FRONTEND }}
        container-name: ${{ env.CONTAINER_NAME_FRONTEND }}
        image: ${{ steps.build-image-frontend.outputs.image }}

    - name: Deploy Amazon ECS task definition (Frontend)
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def-frontend.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE_FRONTEND }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true

    - name: Fill in the new image ID in the Amazon ECS task definition (Backend)
      id: task-def-backend
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.ECS_TASK_DEFINITION_BACKEND }}
        container-name: ${{ env.CONTAINER_NAME_BACKEND }}
        image: ${{ steps.build-image-backend.outputs.image }}

    - name: Deploy Amazon ECS task definition (Backend)
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def-backend.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE_BACKEND }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true

    - name: Fill in the new image ID in the Amazon ECS task definition (Pagos)
      id: task-def-pagos
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.ECS_TASK_DEFINITION_PAGOS }}
        container-name: ${{ env.CONTAINER_NAME_PAGOS }}
        image: ${{ steps.build-image-pagos.outputs.image }}

    - name: Deploy Amazon ECS task definition (Pagos)
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def-pagos.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE_PAGOS }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true
